export const SHOW_QUESTION_FORM = 'SHOW_QUESTION_FORM';
export const SHOW_QUESTION_FORM_SUCCESS = 'SHOW_QUESTION_FORM_SUCCESS';

export const CREATE_ONE_QUESTION = 'CREATE_ONE_QUESTION';
export const CREATE_ONE_QUESTION_SUCCESS = 'CREATE_ONE_QUESTION_SUCCESS';

export const GET_LAST_QUESTION = 'GET_LAST_QUESTION';
export const GET_LAST_QUESTION_SUCCESS = 'GET_LAST_QUESTION_SUCCESS';

export const GET_BEST_QUESTION = 'GET_BEST_QUESTION';
export const GET_BEST_QUESTION_SUCCESS = 'GET_BEST_QUESTION_SUCCESS';