export const TOGGLE_QUESTION_FORM = 'TOGGLE_QUESTION_FORM';
export const TOGGLE_QUESTION_FORM_SUCCESS = 'TOGGLE_QUESTION_FORM_SUCCESS';

export const CREATE_ONE_QUESTION = 'CREATE_ONE_QUESTION';
export const CREATE_ONE_QUESTION_SUCCESS = 'CREATE_ONE_QUESTION_SUCCESS';

export const GET_LAST_QUESTION = 'GET_LAST_QUESTION';
export const GET_LAST_QUESTION_SUCCESS = 'GET_LAST_QUESTION_SUCCESS';

export const GET_BEST_QUESTION = 'GET_BEST_QUESTION';
export const GET_BEST_QUESTION_SUCCESS = 'GET_BEST_QUESTION_SUCCESS';

export const TOGGLE_QUESTION_STATS = 'TOGGLE_QUESTION_STATS';

export const TOGGLE_RESPONSE_FIELD = 'TOGGLE_RESPONSE_FIELD';

export const RESPOND_TO_ONE_QUESTION = 'RESPOND_TO_ONE_QUESTION';
export const RESPOND_TO_ONE_QUESTION_SUCCESS = 'RESPOND_TO_ONE_QUESTION_SUCCESS';

export const PICK_ONE_RESPONSE = 'PICK_ONE_RESPONSE'